spring.application.name=air
tequila.url=https://api.tequila.kiwi.com
tequila.delay-between-requests=3000
tequila.enable-caching=false
neo4j.dbname=air
neo4j.port=7687
neo4j.url=bolt://localhost
airport.csv.data=K://code//airports//data//airports.csv
airport.csv.loadonstartup=false
country.list=AL,DZ,AS,AD,AO,AI,AG,AR,AM,AW,AU,AT,AZ,BS,BH,BB,BE,BZ,BM,BT,BO,BA,BW,BR,BN,BG,CA,CV,KY,CL,CN,CO,CK,CR,HR,CU,CW,CY,CZ,DK,DJ,DM,DO,EC,EG,SV,GQ,EE,SZ,FO,FM,FJ,FI,FR,PF,GA,GE,DE,GH,GR,GL,GD,GU,GT,GY,HN,HK,HU,IS,ID,IR,IQ,IE,IM,IL,IT,CI,JM,JP,JO,KZ,KW,LV,LB,LY,LT,LU,MO,MG,MY,MV,MT,MH,MU,MX,MD,MC,MN,ME,MS,MA,NA,NR,NL,NC,NZ,NI,MP,MK,NO,OM,PW,PA,PY,PE,PH,PL,PT,PR,QA,RO,KN,LC,MF,VC,WS,ST,SA,RS,SC,SG,SX,SK,SI,ZA,KR,ES,LK,SR,SE,CH,TW,TH,TO,TT,TN,TR,TM,TC,TV,UA,AE,GB,US,UY,UZ,VU,VE,VN